/*
 * This source file was generated by the Gradle 'init' task
 */
package todoapp;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appStarts() {
        assertEquals(1, 1);
    }
}
